spring.application.name=backend

# PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://db.tcuxlcyjapaajrqndrbs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Desksphere@125
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb25UaGF0SXNMb25nRW5vdWdoMTIzNDU2Nzg5MDEyMzQ=
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG

# Python AI Service
python.ai.url=http://localhost:8000/chat

# ===============================
# Supabase Storage
# ===============================
supabase.url=https://tcuxlcyjapaajrqndrbs.supabase.co
supabase.bucket=attachments
supabase.service-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdXhsY3lqYXBhYWpycW5kcmJzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MzQ5MzQ4MCwiZXhwIjoyMDk5MDY5NDgwfQ.KHGCMjvCBa2mxbElM04yyKPyS3NwzKU3TtYoh3i_j_8