spring.application.name=backend
spring.datasource.url=jdbc:postgresql://db.tcuxlcyjapaajrqndrbs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Desksphere@125
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Om9ySlhUU2lnbmluZ1SoaXNJc0p1c3RBVGVzdEtleTEyMzQ1Ng==
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

python.ai.url=http://localhost:8000/chat